### ISSUE TITLE
Can this project include the forehead?

### ISSUE THREAD

**Issue by ArtificialZeng** [jhb86253817/PIPNet#51]

**Comment by jhb86253817** [comment]
Hi, it really depends on the training data. If you have data with forehead annotations, you can easily train a model. By now, our model does not supprt this.

**Comment by ArtificialZeng** [comment]
> Hi, it really depends on the training data. If you have data with forehead annotations, you can easily train a model. By now, our model does not supprt this.

thkx for your reply. May I ask if I label a photo with a forehead, is the number of key points fixed? Or will it increase? Where is the function that represents the number of key points?

**Comment by ArtificialZeng** [comment]
> Hi, it really depends on the training data. If you have data with forehead annotations, you can easily train a model. By now, our model does not supprt this.

here is the inference.py code from the torchml project.
when I change the key point number, it gets errors:

Traceback (most recent call last):
  File "inference.py", line 95, in <module>
    landmarks, bboxes = torchlm.runtime.forward(image)
  File "/home/ailab/ai_code/Face/torchlm/torchlm/runtime/_wrappers.py", line 125, in forward
    **kwargs
  File "/home/ailab/ai_code/Face/torchlm/torchlm/runtime/_wrappers.py", line 79, in forward
    lms_pred = cls.landmarks_base.apply_detecting(crop, **kwargs)  # (m,2)
  File "/home/ailab/ai_code/Face/torchlm/torchlm/runtime/ort/_pipnet.py", line 173, in apply_detecting
    outputs_cls = np.reshape(outputs_cls, (self.num_lms, -1))  # (68,64)
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/ailab/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/ailab/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 6272 into shape (99,newaxis)



the keypoints parameter is  num_lms=98 .  I used the PIPNet model. and only wflw dataset, it only has 98 keypoints, forhead not included.

**Comment by jhb86253817** [comment]
> > Hi, it really depends on the training data. If you have data with forehead annotations, you can easily train a model. By now, our model does not supprt this.
> 
> thkx for your reply. May I ask if I label a photo with a forehead, is the number of key points fixed? Or will it increase? Where is the function that represents the number of key points?

The number of key points is related to your annotations. If you combine your added forehead with original 98 landmarks, then it will increase.

**Comment by jhb86253817** [comment]
> > Hi, it really depends on the training data. If you have data with forehead annotations, you can easily train a model. By now, our model does not supprt this.
> 
> here is the inference.py code from the torchml project. when I change the key point number, it gets errors:
> 
> Traceback (most recent call last): File "inference.py", line 95, in landmarks, bboxes = torchlm.runtime.forward(image) File "/home/ailab/ai_code/Face/torchlm/torchlm/runtime/_wrappers.py", line 125, in forward **kwargs File "/home/ailab/ai_code/Face/torchlm/torchlm/runtime/_wrappers.py", line 79, in forward lms_pred = cls.landmarks_base.apply_detecting(crop, **kwargs) # (m,2) File "/home/ailab/ai_code/Face/torchlm/torchlm/runtime/ort/_pipnet.py", line 173, in apply_detecting outputs_cls = np.reshape(outputs_cls, (self.num_lms, -1)) # (68,64) File "<**array_function** internals>", line 6, in reshape File "/home/ailab/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 298, in reshape return _wrapfunc(a, 'reshape', newshape, order=order) File "/home/ailab/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc return bound(*args, **kwds) ValueError: cannot reshape array of size 6272 into shape (99,newaxis)
> 
> the keypoints parameter is num_lms=98 . I used the PIPNet model. and only wflw dataset, it only has 98 keypoints, forhead not included.

This seems from another project, which I'm afraid I cannot answer.
